language: node_js
node_js:
  - stable
install:
  - yarn
script:
  - yarn commitlint --from=HEAD~1
  - yarn build
  - CI=true yarn test --coverage
  - yarn lint
after_success:
  - cat coverage/lcov.info | yarn coveralls
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
